#!/usr/bin/env bash
set -e

echo "Setting password for jupyter-srv..."

sudo -u jupytersrv -H \
env JUPYTER_CONFIG_DIR=/srv/jupyter-srv/config \
/srv/jupyter-srv/venv/bin/python -m jupyter_server.auth password

echo
echo "Password stored in:"
echo "/srv/jupyter-srv/config/jupyter_server_config.json"
echo
echo "Restarting service..."
systemctl restart jupyter-srv.service

echo "Done."
